{module_json,json="/_system/apps/{{appKey}}/_config/manifest.json" collection="appManifest"}
<title>{{appManifest.name}}</title>
<link href="/_System/apps/{{appKey}}/_assets/css/app.css" type="text/css" rel="stylesheet" media="screen" />
<script type="text/javascript" src="//code.jquery.com/jquery-1.10.2.min.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.3.1/jquery.cookie.min.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.5.1/underscore-min.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/backbone.js/1.0.0/backbone-min.js"></script>
<script type="text/javascript" src="//cdn.worldsecuresystems.com/bcapi/bcapi-0.1.0.min.js"></script>
<script type="text/javascript" src="/_System/apps/{{appKey}}/_assets/js/app.js"></script>
<script type="text/javascript" src="/_System/apps/{{appKey}}/_assets/js/jquery.tablesorter.min.js"></script>
{module_json,json="/_System/apps/{{appKey}}/_config/settings.json" collection="appSettings"}