{module_json,json="/_System/apps/solid-app-framework/_config/settings.json" collection="appSettings"}
<ul class="bcam-tabs">
  <li> <a href="index.html">Pages</a> </li>
  <li class="pull-right" style="display: block;"><a href="instructions.html"><span class="glyphicon glyphicon-question-sign"></span> Help </a></li>
  <li class="pull-right" style="display: block;"><a href="settings.html"><span class="glyphicon glyphicon-cog"></span> Settings </a></li>
</ul>