<ol>
	<li id="mPageTitleCount">Missing Page Titles<span class="errorCount"></span></li>
	<li id="sPageTitleCount">Page Title Too Short<span class="errorCount"></span></li>
	<li id="lPageTitleCount">Page Title Too Long<span class="errorCount"></span></li>
	<li id="mPageDescriptionCount">Missing Meta Description<span class="errorCount"></span></li>
	<li id="lPageDescriptionCount">Meta Description Too Long<span class="errorCount"></span></li>
	<li id="bPageURLCount">Bad URL<span class="errorCount"></span></li>
	<li id="lPageURLCount">Long URL<span class="errorCount"></span></li>
	<li id="ePageURLCount">File Extensions in URLs<span class="errorCount"></span></li>
</ol>